FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04

RUN apt-get update && apt-get install -y --no-install-recommends\
    gcc g++ clang\
    cppcheck valgrind clangd ccache\
    cmake ninja-build\
    lsb-release zlib1g-dev\
    wget git
